name: "Template Maker"
version: "1.0.7"
slug: "template_maker"
description: "Maak templates zonder YAML trauma - met visuele interface!"
url: "https://github.com/JOUW-USERNAME/template-maker-pro"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web interface"
webui: "http://[HOST]:[PORT:8099]"
startup: application
boot: auto
hassio_api: true
hassio_role: default
homeassistant_api: true
auth_api: true
options:
  supervisor_token: ""
  confirm_beta: false
  i_have_a_backup: false
  i_wont_complain_on_github: false
schema:
  supervisor_token: password?
  confirm_beta: bool
  i_have_a_backup: bool
  i_wont_complain_on_github: bool
map:
  - config:rw
