name: "Automation Maker"
version: "1.0.0"
slug: "automation_maker"
description: "Eenvoudige automation maker met visuele interface"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Web interface"
webui: "http://[HOST]:[PORT:5000]"
startup: application
boot: auto
hassio_api: true
hassio_role: default
homeassistant_api: true
auth_api: true
ingress: true
ingress_port: 5000
panel_icon: mdi:robot-happy
panel_title: Automation Maker
options:
  automations_path: "/config/include/automations"
  supervisor_token: ""
schema:
  automations_path: str
  supervisor_token: password?
map:
  - config:rw
  - share:rw
